project_name: schema

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/iptecharch/schema-server/version={{.Version}}-{{.ShortCommit}}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - schema-server
    image_templates:
      - "ghcr.io/iptecharch/schema-server:latest"
      - 'ghcr.io/iptecharch/schema-server:{{ replace .Version "v" ""}}'
    dockerfile: Dockerfile
    skip_push: false
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
      386: i386
      arm: armv7
      arm64: aarch64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
