project_name: schema-server
builds:
  - id: schema-server
    binary: schema-server
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
    goos:
      - linux
    goarch:
      - amd64
  - id: schemac
    binary: schemac
    main: ./client/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - schema-server
      - schemac
    image_templates:
      - "ghcr.io/iptecharch/{{ .ProjectName }}:v0.0.0-{{ .ShortCommit }}"
      - "ghcr.io/iptecharch/{{ .ProjectName }}:v0.0.0-dev-latest"
      - "registry.kmrd.dev/iptecharch/{{ .ProjectName }}:v0.0.0-{{ .ShortCommit }}"
      - "registry.kmrd.dev/iptecharch/{{ .ProjectName }}:v0.0.0-dev-latest"
    dockerfile: goreleaser.dockerfile
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--build-arg=USERID=10000"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/iptecharch/{{.ProjectName}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
  - goos: linux
    goarch: amd64
    ids:
      - schema-server
      - schemac
    image_templates:
      - "registry.k8s.hans.io/iptecharch/{{ .ProjectName }}:v0.0.0-{{ .ShortCommit }}"
      - "registry.k8s.hans.io/iptecharch/{{ .ProjectName }}:v0.0.0-dev-latest"
    dockerfile: goreleaser.dockerfile
    skip_push: false
    push_flags:
      - --tls-verify=false
    build_flag_templates:
      - "--pull"
      - "--build-arg=USERID=10000"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/iptecharch/{{.ProjectName}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
release:
  disable: true
